name: Create Vibe Android production build

on:
  push:
    branches: ['main']
    paths:
      - 'mobile/**'

jobs:
  build_android:
    name: Build Vibe Android
    type: build
    params:
      platform: android
      profile: production
