import { FIREBASE_ENABLED, auth, rtdb, databaseRef, onValue, set, push, onDisconnect, databaseServerTimestamp } from './firebase-client.js';

const state = { currentUser: null, currentChatId: null, stopChat: null, stopPresence: null, chats: new Map() };
const $ = (id) => document.getElementById(id);
const toast = (message) => { const el = $('toast'); if (!el) return; el.textContent = message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove('show'), 2600); };
const uid = () => state.currentUser?.uid || auth?.currentUser?.uid || null;
const normalizeId = (value) => String(value || '').trim().replace(/[^A-Za-z0-9_-]/g, '').slice(0, 100);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
const escapeAttr = (value) => escapeHtml(value).replace(/`/g, '&#96;');

function setPresence(user) {
  if (!FIREBASE_ENABLED || !rtdb || !user) return;
  const connectionId = push(databaseRef(rtdb, `presence/${user.uid}/connections`)).key;
  if (!connectionId) return;
  const connectionRef = databaseRef(rtdb, `presence/${user.uid}/connections/${connectionId}`);
  const statusRef = databaseRef(rtdb, `presence/${user.uid}/status`);
  const lastOnlineRef = databaseRef(rtdb, `presence/${user.uid}/lastOnline`);
  set(connectionRef, { connectedAt: databaseServerTimestamp() }).catch(() => {});
  set(statusRef, { state: 'online', updatedAt: databaseServerTimestamp() }).catch(() => {});
  onDisconnect(connectionRef).remove().catch(() => {});
  onDisconnect(statusRef).set({ state: 'offline', updatedAt: databaseServerTimestamp() }).catch(() => {});
  onDisconnect(lastOnlineRef).set(databaseServerTimestamp()).catch(() => {});
}
function stopSubscriptions() { if (state.stopChat) state.stopChat(); state.stopChat = null; if (state.stopPresence) state.stopPresence(); state.stopPresence = null; }
function ensureChatMembership(chatId) { const userId = uid(); if (!userId || !rtdb) return Promise.reject(new Error('Connexion requise.')); return set(databaseRef(rtdb, `chatMembers/${chatId}/${userId}`), true).then(() => set(databaseRef(rtdb, `userChats/${userId}/${chatId}`), true)); }
async function createChat() { const userId = uid(); if (!userId || !rtdb) return toast('Connectez-vous pour créer une discussion.'); const name = prompt('Nom de la discussion :', 'Nouvelle discussion'); if (!name?.trim()) return; const chatId = push(databaseRef(rtdb, 'chats')).key; if (!chatId) return toast('Impossible de créer la discussion.'); await set(databaseRef(rtdb, `chats/${chatId}`), { name: name.trim().slice(0, 80), ownerUid: userId, createdAt: databaseServerTimestamp() }); await ensureChatMembership(chatId); openChat(chatId, { name: name.trim().slice(0, 80), ownerUid: userId }); toast('Discussion créée.'); }
async function joinChat() { const userId = uid(); if (!userId || !rtdb) return toast('Connectez-vous pour rejoindre une discussion.'); const raw = prompt('ID de la discussion :'); const chatId = normalizeId(raw); if (!chatId) return; try { const snapshot = await new Promise((resolve, reject) => { const ref = databaseRef(rtdb, `chats/${chatId}`); const unsubscribe = onValue(ref, resolve, reject, { onlyOnce: true }); setTimeout(() => { try { unsubscribe(); } catch {} reject(new Error('Délai dépassé.')); }, 8000); }); const chat = snapshot.val(); if (!chat) return toast('Discussion introuvable.'); if (chat.ownerUid === userId) { await ensureChatMembership(chatId); openChat(chatId, chat); return; } if (!chat.inviteToken) return toast('Cette discussion nécessite une invitation valide.'); const token = prompt('Code d’invitation :'); if (!token || token.trim() !== String(chat.inviteToken)) return toast('Code d’invitation invalide.'); await ensureChatMembership(chatId); openChat(chatId, chat); } catch (error) { console.error(error); toast('Impossible de rejoindre cette discussion.'); } }
function subscribeChats() { const userId = uid(); if (!FIREBASE_ENABLED || !rtdb || !userId) return; const ref = databaseRef(rtdb, `userChats/${userId}`); state.stopChat = onValue(ref, async (snap) => { const memberships = snap.val() || {}; const entries = Object.keys(memberships); const list = $('conversationList'); if (!list) return; if (!entries.length) { list.innerHTML = ''; return; } const loaded = []; for (const chatId of entries.slice(0, 100)) { try { const chatSnap = await new Promise((resolve, reject) => onValue(databaseRef(rtdb, `chats/${chatId}`), resolve, reject, { onlyOnce: true })); const chat = chatSnap.val(); if (chat && typeof chat === 'object' && typeof chat.name === 'string' && typeof chat.ownerUid === 'string') { state.chats.set(chatId, chat); loaded.push([chatId, chat]); } } catch {} } list.innerHTML = loaded.map(([chatId, chat]) => `<button class="conversation-item" data-chat-id="${escapeAttr(chatId)}"><div class="avatar">${escapeHtml((chat.name || 'V')[0].toUpperCase())}</div><div><strong>${escapeHtml(chat.name || 'Discussion')}</strong><span>Discussion Vibe</span></div></button>`).join(''); list.querySelectorAll('[data-chat-id]').forEach((el) => el.addEventListener('click', () => openChat(el.dataset.chatId, state.chats.get(el.dataset.chatId)))); }, () => toast('Impossible de charger vos discussions.')); }
function openChat(chatId, chat = {}) { state.currentChatId = chatId; $('emptyState')?.classList.add('hidden'); $('chatView')?.classList.remove('hidden'); $('chatName').textContent = chat.name || 'Discussion'; $('chatAvatar').textContent = (chat.name || 'V')[0].toUpperCase(); $('chatPresence').textContent = 'discussion'; subscribeToChat(chatId); }
function renderMessage(m) { const own = m.uid === uid(); const type = String(m.type || 'text'); let body = ''; if (type === 'media' && m.dataUrl) { const url = escapeAttr(m.dataUrl); const name = escapeHtml(m.fileName || 'Fichier'); if (String(m.mimeType || '').startsWith('image/')) body = `<img class="message-media" src="${url}" alt="${name}" loading="lazy">`; else if (String(m.mimeType || '').startsWith('video/')) body = `<video class="message-media" src="${url}" controls preload="metadata"></video>`; else if (String(m.mimeType || '').startsWith('audio/')) body = `<audio src="${url}" controls preload="metadata"></audio>`; else body = `<a class="message-file" href="${url}" download="${escapeAttr(m.fileName || 'fichier')}">📎 ${name}</a>`; } else { body = escapeHtml(m.text || ''); } if (!body) return ''; return `<article class="message ${own ? 'mine' : ''}" data-message="${escapeAttr(m.id)}"><div class="message-bubble">${body}</div></article>`; }
function subscribeToChat(chatId) { if (state.stopChat) state.stopChat(); if (!FIREBASE_ENABLED || !rtdb || !uid()) return; const ref = databaseRef(rtdb, `messages/${chatId}`); state.stopChat = onValue(ref, (snap) => { const messages = snap.val() || {}; const container = $('messages'); if (!container) return; const rows = Object.entries(messages).map(([id, message]) => ({ id, ...message })).filter((m) => m && typeof m.uid === 'string' && (typeof m.text === 'string' || typeof m.dataUrl === 'string')).slice(-200).sort((a,b) => Number(a.createdAt || 0) - Number(b.createdAt || 0)); container.innerHTML = rows.map(renderMessage).join(''); container.scrollTop = container.scrollHeight; }, () => toast('Impossible de charger les messages.')); }
async function sendMessage(event) { event?.preventDefault(); const text = $('messageInput')?.value?.trim(); const userId = uid(); if (!text || !userId || !state.currentChatId || !rtdb) return; if (text.length > 2000) return toast('Message trop long.'); try { const ref = push(databaseRef(rtdb, `messages/${state.currentChatId}`)); await set(ref, { uid: userId, text, type: 'text', createdAt: databaseServerTimestamp() }); $('messageInput').value = ''; } catch { toast('Message non envoyé.'); } }
function addEmoji() { const input = $('messageInput'); if (!input) return; const emojis = ['😀','😂','😍','👍','❤️','🙏','🔥','😎','😢','😮','🎉','👏']; const current = prompt(`Choisir un emoji :\n${emojis.join('  ')}`); if (!current) return; const emoji = [...current].find((c) => emojis.includes(c)); if (!emoji) return toast('Emoji non reconnu.'); const start = input.selectionStart ?? input.value.length; const end = input.selectionEnd ?? input.value.length; input.value = input.value.slice(0, start) + emoji + input.value.slice(end); input.focus(); input.selectionStart = input.selectionEnd = start + emoji.length; }
async function createStory() { const userId = uid(); if (!userId || !rtdb) return toast('Connectez-vous pour publier une actu.'); const text = prompt('Votre actu :'); if (!text?.trim()) return; const storyRef = push(databaseRef(rtdb, `stories/${userId}`)); if (!storyRef.key) return toast('Impossible de publier l’actu.'); await set(storyRef, { uid: userId, text: text.trim().slice(0, 2000), type: 'text', createdAt: databaseServerTimestamp(), expiresAt: Date.now() + 86400000 }); toast('Actu publiée pour 24 h.'); }
function bindUI() { $('newChatBtn')?.addEventListener('click', createChat); $('menuBtn')?.addEventListener('click', () => toast('Menu Vibe')); $('messageForm')?.addEventListener('submit', sendMessage); $('emojiBtn')?.addEventListener('click', addEmoji); $('profileBtn')?.addEventListener('click', () => document.dispatchEvent(new CustomEvent('vibe:open-auth'))); $('backBtn')?.addEventListener('click', () => { state.currentChatId = null; $('chatView')?.classList.add('hidden'); $('emptyState')?.classList.remove('hidden'); stopSubscriptions(); subscribeChats(); }); document.querySelectorAll('.tab').forEach((tab) => tab.addEventListener('click', () => { document.querySelectorAll('.tab').forEach((x) => x.classList.remove('active')); tab.classList.add('active'); if (tab.dataset.view === 'status') createStory(); if (tab.dataset.view === 'chats') subscribeChats(); })); }
bindUI();
document.addEventListener('vibe:auth-changed', (event) => { stopSubscriptions(); state.currentUser = event.detail?.user || auth?.currentUser || null; if (state.currentUser) { setPresence(state.currentUser); subscribeChats(); } });
window.VibeApp = { createChat, joinChat, createStory, openChat };
