import{getApps}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import{getAuth}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import{getFirestore,doc,collection,addDoc,setDoc,updateDoc,onSnapshot,query,where,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps()[0],auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const RTC_CONFIG={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302','stun:stun2.l.google.com:19302']},...(globalThis.VIBE_TURN_SERVERS||firebaseConfig.turnServers||[])]};
let peer=null,stream=null,remote=null,callRef=null,callUnsub=null,iceUnsub=null,incoming=null,state='IDLE',incomingListener=null,ringTimer=null,listeningUid=null,currentVideo=false,muted=false,cameraOff=false;
const toast=t=>{const e=$('toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window.__callToast);window.__callToast=setTimeout(()=>e.style.display='none',3000)};
function ensureControls(){const box=document.querySelector('.call-buttons');if(!box||document.getElementById('callMute'))return;const mute=document.createElement('button');mute.id='callMute';mute.className='call-control';mute.type='button';mute.title='Couper le micro';mute.innerHTML='<i class="fa-solid fa-microphone"></i>';const cam=document.createElement('button');cam.id='callCamera';cam.className='call-control';cam.type='button';cam.title='Couper la caméra';cam.innerHTML='<i class="fa-solid fa-video"></i>';mute.hidden=true;cam.hidden=true;mute.onclick=toggleMute;cam.onclick=toggleCamera;box.insertBefore(mute,box.firstChild);box.insertBefore(cam,mute.nextSibling)}
function setControls(connected,video){ensureControls();const m=$('callMute'),c=$('callCamera');if(m)m.hidden=!connected;if(c)c.hidden=!connected||!video;if(m){m.classList.toggle('is-off',muted);m.innerHTML=`<i class="fa-solid ${muted?'fa-microphone-slash':'fa-microphone'}"></i>`;m.title=muted?'Réactiver le micro':'Couper le micro'}if(c){c.classList.toggle('is-off',cameraOff);c.innerHTML=`<i class="fa-solid ${cameraOff?'fa-video-slash':'fa-video'}"></i>`;c.title=cameraOff?'Réactiver la caméra':'Couper la caméra'}}
function cleanup(){clearTimeout(ringTimer);ringTimer=null;callUnsub?.();iceUnsub?.();callUnsub=null;iceUnsub=null;peer?.close();peer=null;stream?.getTracks().forEach(t=>t.stop());stream=null;remote=null;callRef=null;incoming=null;state='IDLE';currentVideo=false;muted=false;cameraOff=false;if($('callOverlay'))$('callOverlay').hidden=true;if($('remoteVideo'))$('remoteVideo').srcObject=null;if($('localVideo'))$('localVideo').srcObject=null;if($('acceptCall'))$('acceptCall').hidden=false;if($('rejectCall'))$('rejectCall').hidden=false;if($('endCall'))$('endCall').hidden=true;setControls(false,false)}
function show(title,status,answerMode,video=currentVideo){$('callTitle').textContent=title;$('callStatus').textContent=status;$('callOverlay').hidden=false;$('acceptCall').hidden=!answerMode;$('rejectCall').hidden=!answerMode;$('endCall').hidden=answerMode;setControls(!answerMode&&state==='CONNECTED',video);if($('localVideo'))$('localVideo').hidden=!video;if($('remoteVideo'))$('remoteVideo').hidden=!video}
function watchPeer(video){if(!peer)return;peer.onconnectionstatechange=()=>{const s=peer.connectionState;if(s==='connected'){state='CONNECTED';$('callStatus').textContent='Connecté';setControls(true,video)}else if(s==='connecting')$('callStatus').textContent='Connexion…';else if(['failed','disconnected'].includes(s)){if(s==='failed')toast('Connexion d’appel perdue. Vérifie ton réseau.');setTimeout(()=>{if(state!=='IDLE'&&peer?.connectionState===s)end('ended')},s==='failed'?1500:5000)}else if(s==='closed')cleanup()};peer.oniceconnectionstatechange=()=>{if(peer.iceConnectionState==='failed')peer.restartIce?.()};peer.ontrack=e=>{if(!remote||!e.streams?.[0])return;e.streams[0].getTracks().forEach(t=>{if(!remote.getTracks().some(x=>x.id===t.id))remote.addTrack(t)})}}
async function start(video,target){if(state!=='IDLE')return toast('Un appel est déjà en cours.');if(!target||target.group||target.channel)return toast('Les appels sont disponibles uniquement entre deux utilisateurs.');const u=auth.currentUser;if(!u||u.uid!==uidSafe())return toast('Reconnecte-toi avant d’appeler.');if(!navigator.mediaDevices?.getUserMedia)return toast('Ton navigateur ne permet pas les appels audio/vidéo.');try{state='RINGING';currentVideo=!!video;stream=await navigator.mediaDevices.getUserMedia({audio:true,video:!!video});$('localVideo').srcObject=stream;peer=new RTCPeerConnection(RTC_CONFIG);remote=new MediaStream();$('remoteVideo').srcObject=remote;watchPeer(!!video);stream.getTracks().forEach(t=>peer.addTrack(t,stream));callRef=doc(collection(db,'calls'));peer.onicecandidate=e=>e.candidate&&addDoc(collection(callRef,'candidates-caller'),e.candidate.toJSON()).catch(()=>{});const offer=await peer.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:!!video});await peer.setLocalDescription(offer);await setDoc(callRef,{caller:u.uid,callee:target.uid,type:video?'video':'audio',offer:{type:offer.type,sdp:offer.sdp},status:'ringing',createdAt:serverTimestamp(),expiresAt:Date.now()+45000});iceUnsub=onSnapshot(collection(callRef,'candidates-callee'),s=>s.docChanges().forEach(ch=>{if(ch.type==='added')peer?.addIceCandidate(ch.doc.data()).catch(()=>{})}));callUnsub=onSnapshot(callRef,async s=>{const c=s.data();if(!c)return;if(c.answer&&!peer.currentRemoteDescription){await peer.setRemoteDescription(c.answer);state='CONNECTED';show(video?'Appel vidéo':'Appel audio','Connecté',false,!!video)}if(['rejected','ended','expired'].includes(c.status))cleanup()});show(video?'Appel vidéo…':'Appel audio…','Appel en cours…',false,!!video);ringTimer=setTimeout(()=>state!=='IDLE'&&end('expired'),45000)}catch(e){cleanup();toast('Appel impossible : '+(e?.message||'erreur'))}}
function uidSafe(){return auth.currentUser?.uid||null}
async function accept(){const c=incoming,u=auth.currentUser;if(!c||!u||u.uid!==c.callee)return;try{state='CONNECTED';currentVideo=c.type==='video';callRef=doc(db,'calls',c.id);stream=await navigator.mediaDevices.getUserMedia({audio:true,video:currentVideo});$('localVideo').srcObject=stream;peer=new RTCPeerConnection(RTC_CONFIG);remote=new MediaStream();$('remoteVideo').srcObject=remote;watchPeer(currentVideo);stream.getTracks().forEach(t=>peer.addTrack(t,stream));peer.onicecandidate=e=>e.candidate&&addDoc(collection(callRef,'candidates-callee'),e.candidate.toJSON()).catch(()=>{});iceUnsub=onSnapshot(collection(callRef,'candidates-caller'),s=>s.docChanges().forEach(ch=>{if(ch.type==='added')peer?.addIceCandidate(ch.doc.data()).catch(()=>{})}));await peer.setRemoteDescription(c.offer);const answer=await peer.createAnswer({offerToReceiveAudio:true,offerToReceiveVideo:currentVideo});await peer.setLocalDescription(answer);await updateDoc(callRef,{answer:{type:answer.type,sdp:answer.sdp},status:'accepted',acceptedAt:serverTimestamp()});callUnsub=onSnapshot(callRef,s=>{if(['ended','rejected','expired'].includes(s.data()?.status))cleanup()});show(currentVideo?'Appel vidéo':'Appel audio','Connexion…',false,currentVideo)}catch(e){await updateDoc(callRef,{status:'rejected'}).catch(()=>{});cleanup();toast('Impossible d’accepter l’appel : '+(e?.message||'erreur'))}}
function toggleMute(){if(!stream)return;muted=!muted;stream.getAudioTracks().forEach(t=>t.enabled=!muted);setControls(true,currentVideo)}
function toggleCamera(){if(!stream||!currentVideo)return;cameraOff=!cameraOff;stream.getVideoTracks().forEach(t=>t.enabled=!cameraOff);setControls(true,true)}
async function end(status='ended'){clearTimeout(ringTimer);ringTimer=null;const r=callRef;if(r)await updateDoc(r,{status,endedAt:serverTimestamp()}).catch(()=>{});cleanup()}
function listen(){stopListening();const u=auth.currentUser;if(!u)return()=>{};listeningUid=u.uid;incomingListener=onSnapshot(query(collection(db,'calls'),where('callee','==',u.uid)),s=>s.docChanges().forEach(ch=>{const c=ch.doc.data();if(ch.type!=='added'||c.status!=='ringing'||state!=='IDLE')return;if(c.expiresAt&&c.expiresAt<Date.now()){updateDoc(ch.doc.ref,{status:'expired'}).catch(()=>{});return}incoming={id:ch.doc.id,...c};state='RINGING';currentVideo=c.type==='video';show(c.type==='video'?'Appel vidéo entrant':'Appel audio entrant','Quelqu’un vous appelle',true,currentVideo);ringTimer=setTimeout(()=>state!=='IDLE'&&end('expired'),Math.max(1000,(c.expiresAt||Date.now()+45000)-Date.now()))},e=>console.warn('VIBE calls listener:',e));return stopListening}
function stopListening(){incomingListener?.();incomingListener=null;listeningUid=null;if(state==='RINGING'&&!callRef)cleanup()}
window.VIBE_CALL=video=>start(video,window.VIBE_CURRENT_USER);
window.VIBE_INCOMING=c=>{if(state!=='IDLE')return;incoming=c;state='RINGING';currentVideo=c.type==='video';show(c.type==='video'?'Appel vidéo entrant':'Appel audio entrant','Quelqu’un vous appelle',true,currentVideo)};
window.VIBE_LISTEN_CALLS=listen;window.VIBE_STOP_LISTEN_CALLS=stopListening;
$('audioCall')?.addEventListener('click',()=>window.VIBE_CALL?.(false));$('videoCall')?.addEventListener('click',()=>window.VIBE_CALL?.(true));$('acceptCall')?.addEventListener('click',accept);$('rejectCall')?.addEventListener('click',()=>end('rejected'));$('endCall')?.addEventListener('click',()=>end('ended'));$('callClose')?.addEventListener('click',()=>end('ended'));ensureControls();
