import{getApps}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import{getAuth}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import{getFirestore,doc,collection,addDoc,setDoc,updateDoc,onSnapshot,query,where,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import{firebaseConfig}from'./firebase-config.js';
const app=getApps()[0],auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const RTC_CONFIG={iceServers:[{urls:['stun:stun.l.google.com:19302','stun:stun1.l.google.com:19302','stun:stun2.l.google.com:19302']},...(globalThis.VIBE_TURN_SERVERS||firebaseConfig.turnServers||[])]};
let peer=null,stream=null,remote=null,callRef=null,callUnsub=null,iceUnsub=null,incoming=null,state='IDLE',incomingListener=null,ringTimer=null;
const toast=t=>{const e=$('toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window.__callToast);window.__callToast=setTimeout(()=>e.style.display='none',3000)};
function cleanup(){clearTimeout(ringTimer);ringTimer=null;callUnsub?.();iceUnsub?.();callUnsub=null;iceUnsub=null;peer?.close();peer=null;stream?.getTracks().forEach(t=>t.stop());stream=null;remote=null;callRef=null;incoming=null;state='IDLE';if($('callOverlay'))$('callOverlay').hidden=true;if($('remoteVideo'))$('remoteVideo').srcObject=null;if($('localVideo'))$('localVideo').srcObject=null;if($('acceptCall'))$('acceptCall').hidden=false;if($('rejectCall'))$('rejectCall').hidden=false;if($('endCall'))$('endCall').hidden=true}
function show(title,status,answerMode){$('callTitle').textContent=title;$('callStatus').textContent=status;$('callOverlay').hidden=false;$('acceptCall').hidden=!answerMode;$('rejectCall').hidden=!answerMode;$('endCall').hidden=answerMode}
function watchPeer(video){if(!peer)return;peer.onconnectionstatechange=()=>{const s=peer.connectionState;if(s==='connected'){state='CONNECTED';$('callStatus').textContent='Connecté'}else if(s==='connecting')$('callStatus').textContent='Connexion…';else if(['failed','disconnected'].includes(s)){if(s==='failed')toast('Connexion d’appel perdue. Vérifie ton réseau.');setTimeout(()=>{if(state!=='IDLE'&&peer?.connectionState===s)end('ended')},s==='failed'?1500:5000)}else if(s==='closed')cleanup()};peer.oniceconnectionstatechange=()=>{if(peer.iceConnectionState==='failed')peer.restartIce?.()};peer.ontrack=e=>e.streams[0]?.getTracks().forEach(t=>remote?.addTrack(t))}
async function start(video,target){if(state!=='IDLE')return toast('Un appel est déjà en cours.');if(!target||target.group)return toast('Les appels de groupe ne sont pas encore disponibles.');try{state='RINGING';stream=await navigator.mediaDevices.getUserMedia({audio:true,video});$('localVideo').srcObject=stream;peer=new RTCPeerConnection(RTC_CONFIG);remote=new MediaStream();$('remoteVideo').srcObject=remote;watchPeer(video);stream.getTracks().forEach(t=>peer.addTrack(t,stream));callRef=doc(collection(db,'calls'));peer.onicecandidate=e=>e.candidate&&addDoc(collection(callRef,'candidates-caller'),e.candidate.toJSON());const offer=await peer.createOffer();await peer.setLocalDescription(offer);await setDoc(callRef,{caller:auth.currentUser.uid,callee:target.uid,type:video?'video':'audio',offer:{type:offer.type,sdp:offer.sdp},status:'ringing',createdAt:serverTimestamp(),expiresAt:Date.now()+45000});iceUnsub=onSnapshot(collection(callRef,'candidates-callee'),s=>s.docChanges().forEach(ch=>ch.type==='added'&&peer?.addIceCandidate(ch.doc.data()).catch(()=>{})));callUnsub=onSnapshot(callRef,async s=>{const c=s.data();if(!c)return;if(c.answer&&!peer.currentRemoteDescription){await peer.setRemoteDescription(c.answer);state='CONNECTED';show(video?'Appel vidéo':'Appel audio','Connecté',false)}if(['rejected','ended','expired'].includes(c.status))cleanup()});show(video?'Appel vidéo…':'Appel audio…','Recherche de l’autre utilisateur…',false);ringTimer=setTimeout(()=>state!=='IDLE'&&end('expired'),45000)}catch(e){cleanup();toast('Appel impossible : '+(e?.message||'erreur'))}}
async function accept(){const c=incoming;if(!c)return;try{state='CONNECTED';callRef=doc(db,'calls',c.id);stream=await navigator.mediaDevices.getUserMedia({audio:true,video:c.type==='video'});$('localVideo').srcObject=stream;peer=new RTCPeerConnection(RTC_CONFIG);remote=new MediaStream();$('remoteVideo').srcObject=remote;watchPeer(c.type==='video');stream.getTracks().forEach(t=>peer.addTrack(t,stream));peer.onicecandidate=e=>e.candidate&&addDoc(collection(callRef,'candidates-callee'),e.candidate.toJSON());iceUnsub=onSnapshot(collection(callRef,'candidates-caller'),s=>s.docChanges().forEach(ch=>ch.type==='added'&&peer?.addIceCandidate(ch.doc.data()).catch(()=>{})));await peer.setRemoteDescription(c.offer);const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await updateDoc(callRef,{answer:{type:answer.type,sdp:answer.sdp},status:'accepted',acceptedAt:serverTimestamp()});callUnsub=onSnapshot(callRef,s=>{if(['ended','rejected','expired'].includes(s.data()?.status))cleanup()});show(c.type==='video'?'Appel vidéo':'Appel audio','Connecté',false);incoming=null}catch(e){await updateDoc(callRef,{status:'rejected'}).catch(()=>{});cleanup();toast('Impossible d’accepter l’appel : '+(e?.message||'erreur'))}}
async function end(status='ended'){clearTimeout(ringTimer);ringTimer=null;const r=callRef;if(r)await updateDoc(r,{status,endedAt:serverTimestamp()}).catch(()=>{});cleanup()}
function listen(){const u=auth.currentUser;if(!u)return()=>{};incomingListener?.();incomingListener=onSnapshot(query(collection(db,'calls'),where('callee','==',u.uid)),s=>s.docChanges().forEach(ch=>{const c=ch.doc.data();if(ch.type!=='added'||c.status!=='ringing'||state!=='IDLE')return;if(c.expiresAt&&c.expiresAt<Date.now()){updateDoc(ch.doc.ref,{status:'expired'}).catch(()=>{});return}incoming={id:ch.doc.id,...c};state='RINGING';show(c.type==='video'?'Appel vidéo entrant':'Appel audio entrant','Quelqu’un vous appelle',true);ringTimer=setTimeout(()=>state!=='IDLE'&&end('expired'),Math.max(1000,(c.expiresAt||Date.now()+45000)-Date.now()))}));return()=>{incomingListener?.();incomingListener=null}}
window.VIBE_CALL=video=>start(video,window.VIBE_CURRENT_USER);
window.VIBE_INCOMING=c=>{if(state!=='IDLE')return;incoming=c;state='RINGING';show(c.type==='video'?'Appel vidéo entrant':'Appel audio entrant','Quelqu’un vous appelle',true)};
window.VIBE_LISTEN_CALLS=listen;
$('audioCall')?.addEventListener('click',()=>window.VIBE_CALL?.(false));
$('videoCall')?.addEventListener('click',()=>window.VIBE_CALL?.(true));
$('acceptCall')?.addEventListener('click',accept);
$('rejectCall')?.addEventListener('click',()=>end('rejected'));
$('endCall')?.addEventListener('click',()=>end('ended'));
$('callClose')?.addEventListener('click',()=>end('ended'));
