import{getApp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import{getAuth}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import{getFirestore,collection,getDocs,doc,updateDoc}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const $=id=>document.getElementById(id);
const toast=t=>{const e=$('toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window.__vibeFixToast);window.__vibeFixToast=setTimeout(()=>e.style.display='none',2400)};
const safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function applySearch(){const s=$('search'),b=$('contacts');if(!s||!b)return;const term=s.value.trim().toLocaleLowerCase('fr-FR');if($('clearSearch'))$('clearSearch').hidden=!term;let n=0;b.querySelectorAll('.contact').forEach(x=>{const ok=!term||(x.dataset.search||x.textContent||'').toLocaleLowerCase('fr-FR').includes(term);x.hidden=!ok;if(ok)n++});let e=b.querySelector('.vibe-search-empty');if(term&&!n){if(!e){e=document.createElement('div');e.className='empty vibe-search-empty';b.appendChild(e)}e.innerHTML='<i class="fa-solid fa-magnifying-glass"></i><b>Aucun utilisateur trouvé</b><small>Essaie un autre nom.</small>';e.style.display='grid'}else if(e)e.style.display='none'}
async function openVibeUsers(){const modal=$('modal'),content=$('modalContent');if(!modal||!content)return;content.innerHTML='<div class="vibe-users-panel"><div class="vibe-users-head"><div class="vibe-settings-icon"><i class="fa-solid fa-users"></i></div><div><h2>Utilisateurs VIBE</h2><p>Choisis une personne pour démarrer une discussion.</p></div></div><div id="vibeUsersList" class="vibe-users-list"><div class="empty">Chargement des utilisateurs…</div></div></div>';if(!modal.open)modal.showModal();const list=$('vibeUsersList');try{const auth=getAuth(getApp()),db=getFirestore(getApp()),me=auth.currentUser,snap=await getDocs(collection(db,'users')),users=[];snap.forEach(d=>{const u=d.data();if(!me||u.uid!==me.uid)users.push(u)});users.sort((a,b)=>(a.name||a.email||'').localeCompare(b.name||b.email||'','fr'));if(!users.length){list.innerHTML='<div class="empty"><i class="fa-solid fa-user-slash"></i><b>Aucun autre utilisateur VIBE</b><small>Les comptes VIBE apparaîtront ici automatiquement.</small></div>';return}list.innerHTML='';users.forEach(u=>{const x=document.createElement('button');x.type='button';x.className='vibe-user-item';x.innerHTML=`<img src="${safe(u.avatar||'https://i.pravatar.cc/100?img=12')}" alt=""><span><b>${safe(u.name||u.email||'Utilisateur')}</b><small>${u.online?'🟢 En ligne':'⚪ Hors ligne'}</small></span><i class="fa-solid fa-chevron-right"></i>`;x.onclick=()=>{modal.close();if(typeof window.openChat==='function')window.openChat({uid:u.uid,name:u.name||u.email||'Utilisateur',avatar:u.avatar,group:false});else toast('Impossible d’ouvrir cette discussion.')};list.appendChild(x)})}catch(e){list.innerHTML='<div class="empty"><i class="fa-solid fa-triangle-exclamation"></i><b>Impossible de charger les utilisateurs</b><small>Vérifie ta connexion et les règles Firestore.</small></div>';toast('Impossible de charger les utilisateurs.')}}
function openSettings(){const modal=$('modal'),content=$('modalContent');if(!modal||!content)return;const name=$('meName')?.textContent||'Utilisateur',avatar=$('meAvatar')?.src||$('railAvatar')?.src||'https://i.pravatar.cc/150?img=12';content.innerHTML=`<div class="vibe-settings-panel"><div class="vibe-settings-head"><img class="vibe-settings-avatar" src="${safe(avatar)}" alt="Profil"><div><h2>${safe(name)}</h2><p>Compte VIBE · En ligne</p></div></div><div class="vibe-settings-title">Paramètres</div><button class="vibe-setting-row" id="settingsProfile" type="button"><i class="fa-solid fa-user"></i><span>Mon profil</span><small>Modifier</small></button><button class="vibe-setting-row" id="settingsTheme" type="button"><i class="fa-solid fa-moon"></i><span>Apparence</span><small>${document.body.classList.contains('dark')?'Sombre':'Clair'}</small></button><button class="vibe-setting-row vibe-setting-danger" id="settingsLogout" type="button"><i class="fa-solid fa-right-from-bracket"></i><span>Se déconnecter</span><small>Quitter ce compte</small></button></div>`;modal.showModal();$('settingsProfile').onclick=openProfileSettings;$('settingsTheme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('vibe-theme',document.body.classList.contains('dark')?'dark':'light');$('settingsTheme').querySelector('small').textContent=document.body.classList.contains('dark')?'Sombre':'Clair'};$('settingsLogout').onclick=()=>{$('logout')?.click()}}
function openProfileSettings(){const modal=$('modal'),content=$('modalContent'),name=$('meName')?.textContent||'Utilisateur',avatar=$('meAvatar')?.src||$('railAvatar')?.src||'https://i.pravatar.cc/150?img=12';content.innerHTML=`<div class="vibe-profile-card"><div class="vibe-profile-hero"><img class="vibe-profile-avatar" src="${safe(avatar)}" alt="Profil"><div><h2>${safe(name)}</h2><p>Compte VIBE</p><span class="vibe-profile-status"><i class="fa-solid fa-circle"></i> En ligne</span></div></div><div class="vibe-profile-actions"><button class="vibe-profile-action" id="rename" type="button"><i class="fa-solid fa-pen"></i><span>Modifier mon nom</span></button><button class="vibe-profile-action" id="backSettings" type="button"><i class="fa-solid fa-gear"></i><span>Paramètres du compte</span></button></div></div>`;modal.showModal();$('rename').onclick=async()=>{const n=prompt('Nouveau nom :',name);if(!n?.trim())return;try{const auth=getAuth(getApp()),user=auth.currentUser;if(user?.uid)await updateDoc(doc(getFirestore(getApp()),'users',user.uid),{name:n.trim()});if($('meName'))$('meName').textContent=n.trim();toast('Profil mis à jour.')}catch(e){toast('Impossible de modifier le profil.')}};$('backSettings').onclick=()=>{modal.close();openSettings()}}
function setup(){const s=$('search'),clear=$('clearSearch');if(s){s.addEventListener('input',applySearch,true);s.addEventListener('keyup',applySearch,true);s.addEventListener('keydown',e=>{if(e.key==='Escape'){s.value='';applySearch();s.blur()}})}if(clear&&s)clear.onclick=()=>{s.value='';applySearch();s.focus()};const contacts=$('contacts');if(contacts)new MutationObserver(applySearch).observe(contacts,{childList:true,subtree:true});
if($('railSettings'))$('railSettings').addEventListener('click',openSettings);
if($('railProfile'))$('railProfile').addEventListener('click',openSettings);
if($('newGroupQuick'))$('newGroupQuick').addEventListener('click',()=>{if($('newGroup'))$('newGroup').click()});
if($('newStatusQuick'))$('newStatusQuick').addEventListener('click',()=>{const t=prompt('Écris ton statut :');if(!t?.trim())return;localStorage.setItem('vibe-status',t.trim());renderStatus(t.trim());document.querySelector('.tab[data-tab="stories"]')?.click();toast('Statut publié')});
function renderStatus(text){const box=$('stories');if(box)box.innerHTML=`<div class="empty"><i class="fa-solid fa-circle-notch"></i><b>Ton statut</b><small>${safe(text)}</small></div>`}
const saved=localStorage.getItem('vibe-status');if(saved)renderStatus(saved);
document.querySelectorAll('.tabs .tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const chats=$('contacts'),stories=$('stories');if(t.dataset.tab==='stories'){if(chats)chats.hidden=true;if(stories)stories.hidden=false}else{if(chats)chats.hidden=false;if(stories)stories.hidden=true}}));
const tab=n=>document.querySelector(`.tab[data-tab="${n}"]`)?.click();
if($('railChats'))$('railChats').addEventListener('click',()=>tab('chats'));
if($('railStories'))$('railStories').addEventListener('click',()=>tab('stories'));
if($('railFavorites'))$('railFavorites').addEventListener('click',()=>{tab('chats');toast('Les favoris seront affichés ici.')});
if($('railArchive'))$('railArchive').addEventListener('click',()=>{tab('chats');toast('Les discussions archivées seront affichées ici.')});
if($('railCommunities'))$('railCommunities').addEventListener('click',()=>toast('Communautés VIBE — bientôt disponibles.'));
const close=$('closeModal');if(close)close.addEventListener('click',()=>modal?.close());
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
window.VIBE_SEARCH=applySearch;window.VIBE_OPEN_USERS=openVibeUsers;