import{getApps}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';import{getAuth,updateProfile}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';import{getFirestore,doc,setDoc,serverTimestamp}from'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';import{firebaseConfig}from'./firebase-config.js';
const app=getApps()[0],auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id),fallback='https://i.pravatar.cc/150?img=12';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=t=>{const e=$('toast');if(!e)return;e.textContent=t;e.style.display='block';clearTimeout(window.__vibeCoreToast);window.__vibeCoreToast=setTimeout(()=>e.style.display='none',2600)};
const close=()=>{const m=$('modal');if(m?.open)m.close()};
function panel(title,html,wide=false){const m=$('modal'),c=$('modalContent');if(!m||!c)return;c.innerHTML=`<section class="vibe-native-panel ${wide?'wide':''}"><header><button id="vcoreBack" type="button" aria-label="Retour">‹</button><div><strong>${esc(title)}</strong><small>VIBE · vue interne</small></div><button id="vcoreClose" type="button" aria-label="Fermer">×</button></header><div class="vnp-body">${html}</div></section>`;m.showModal();$('vcoreBack').onclick=close;$('vcoreClose').onclick=close}
function newChat(){const items=[...document.querySelectorAll('#contacts .contact')];if(!items.length)return toast('Aucun contact disponible.');panel('Nouvelle discussion',`<div class="vnp-list">${items.map((x,i)=>{const img=x.querySelector('img')?.src||fallback,name=x.querySelector('b')?.textContent||'Utilisateur';return `<button class="vnp-person" data-i="${i}"><img src="${esc(img)}" alt=""><span><b>${esc(name)}</b><small>Ouvrir la discussion</small></span><i>›</i></button>`}).join('')}</div>`);document.querySelectorAll('.vnp-person').forEach(b=>b.onclick=()=>{items[+b.dataset.i]?.click();close()})}
function createStatus(){panel('Nouveau statut',`<div class="vnp-form"><label>Votre statut<textarea id="vcoreStatus" maxlength="700" placeholder="Quoi de neuf ?"></textarea></label><button id="vcorePublish" class="primary-action" type="button">Publier le statut</button></div>`);$('vcorePublish').onclick=async()=>{const text=$('vcoreStatus')?.value.trim(),u=auth.currentUser;if(!u||!text)return toast('Écris un statut.');try{await import('https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js').then(async({addDoc,collection})=>addDoc(collection(db,'stories'),{uid:u.uid,text,createdAt:serverTimestamp(),expiresAt:new Date(Date.now()+86400000)}));close();toast('Statut publié.')}catch(e){toast('Publication impossible : '+(e?.message||'Erreur Firebase'))}}}
function settings(){panel('Paramètres',`<div class="vnp-settings"><button id="vcoreTheme"><b>🌙 Thème</b><span>${document.body.classList.contains('dark')?'Sombre':'Clair'}</span></button><button id="vcoreProfile"><b>👤 Mon profil</b><span>›</span></button><button id="vcoreClear"><b>🔎 Effacer la recherche</b><span>›</span></button><button id="vcoreAbout"><b>ℹ️ À propos de VIBE</b><span>›</span></button></div>`);$('vcoreTheme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('vibe-theme',document.body.classList.contains('dark')?'dark':'light');settings()};$('vcoreProfile').onclick=profile;$('vcoreClear').onclick=()=>{$('search').value='';$('clearSearch')?.click();close();toast('Recherche effacée.')};$('vcoreAbout').onclick=()=>panel('À propos de VIBE',`<div class="spa-about"><div class="spa-v">V</div><h3>VIBE</h3><p>Messagerie moderne en temps réel.</p><small>Application SPA · Firebase · VIBE AI</small></div>`)}
function profile(){const u=auth.currentUser;if(!u)return toast('Connecte-toi pour ouvrir ton profil.');const name=$('meName')?.textContent||u.displayName||u.email?.split('@')[0]||'Utilisateur',avatar=u.photoURL||$('meAvatar')?.src||fallback;panel('Mon profil',`<div class="spa-profile"><img src="${esc(avatar)}" alt=""><h3>${esc(name)}</h3><p>${esc(u.email||'Compte VIBE')}</p><button id="vcoreRename" class="primary-action" type="button">Modifier mon nom</button></div>`);$('vcoreRename').onclick=()=>panel('Modifier mon nom',`<div class="vnp-form"><label>Nouveau nom<input id="vcoreName" maxlength="60" value="${esc(name)}"></label><button id="vcoreSaveName" class="primary-action" type="button">Enregistrer</button></div>`);$('vcoreSaveName').onclick=async()=>{const n=$('vcoreName')?.value.trim();if(!n)return toast('Entre un nom.');try{await updateProfile(u,{displayName:n});await setDoc(doc(db,'users',u.uid),{uid:u.uid,name:n,email:u.email||'',avatar:u.photoURL||avatar,online:true,updatedAt:serverTimestamp()},{merge:true});$('meName').textContent=n;close();toast('Nom modifié.')}catch(e){toast('Modification impossible : '+(e?.message||'Erreur Firebase'))}}}
function chatSearch(){const input=document.createElement('input');input.className='vnp-search';input.placeholder='Rechercher dans cette discussion…';const results=document.createElement('div');results.className='vnp-results';const render=()=>{const q=input.value.trim().toLocaleLowerCase('fr-FR');const msgs=[...document.querySelectorAll('#messages .msg')].filter(x=>q&&!x.classList.contains('deleted')&&x.textContent.toLocaleLowerCase('fr-FR').includes(q));results.innerHTML=msgs.length?msgs.map((x,i)=>`<button data-i="${i}">${esc(x.querySelector('.message-text')?.textContent||x.textContent.trim())}</button>`).join(''):'<div class="vnp-empty">Aucun résultat.</div>';results.querySelectorAll('button').forEach(b=>b.onclick=()=>{msgs[+b.dataset.i]?.scrollIntoView({behavior:'smooth',block:'center'});close()})};panel(`Recherche · ${$('name')?.textContent||'Discussion'}`,`<div id="vcoreSearchBox"></div><div id="vcoreResults"></div>`);$('vcoreSearchBox').appendChild(input);$('vcoreResults').appendChild(results);input.oninput=render;input.focus();render()}
function mediaViewer(el){const src=el.currentSrc||el.src;if(!src)return;let html='';if(el.tagName==='IMG')html=`<div class="spa-media-stage"><img src="${esc(src)}" alt="Aperçu"></div>`;else if(el.tagName==='VIDEO')html=`<div class="spa-media-stage"><video src="${esc(src)}" controls autoplay playsinline></video></div>`;else if(el.tagName==='AUDIO')html=`<div class="spa-media-stage audio"><audio src="${esc(src)}" controls autoplay></audio></div>`;else return;panel('Média',html,true)}
function fileViewer(a){const src=a.href;if(!src)return;panel(a.textContent?.trim()||'Fichier',`<div class="spa-file-stage"><iframe src="${esc(src)}" title="Aperçu du fichier"></iframe><p>Le fichier reste accessible dans VIBE même si son format ne permet pas une prévisualisation.</p></div>`,true)}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest?.('button');const id=b?.id;if(id==='newChat'){e.preventDefault();e.stopImmediatePropagation();newChat();return}if(id==='newStatusQuick'){e.preventDefault();e.stopImmediatePropagation();createStatus();return}if(id==='railSettings'){e.preventDefault();e.stopImmediatePropagation();settings();return}if(id==='railProfile'){e.preventDefault();e.stopImmediatePropagation();profile();return}if(id==='chatMenu'){e.preventDefault();e.stopImmediatePropagation();chatSearch();return}if(id==='audioCall'||id==='videoCall'){e.preventDefault();e.stopImmediatePropagation();window.VIBE_CALL?window.VIBE_CALL(id==='videoCall'):toast('Service d’appel indisponible.');return}const media=e.target.closest?.('#messages img.media,#messages video.media,#messages audio');if(media){e.preventDefault();e.stopImmediatePropagation();mediaViewer(media);return}const file=e.target.closest?.('#messages a.file-link');if(file){e.preventDefault();e.stopImmediatePropagation();fileViewer(file);return}},true);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.VIBE_CORE={close,newChat,createStatus,settings,profile,chatSearch,mediaViewer,fileViewer}}
window.addEventListener('DOMContentLoaded',bind);
