import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getFirestore, collection, getDocs, addDoc, serverTimestamp, query, limit } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
import { getApps } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-storage.js';
const app=getApps()[0],auth=getAuth(app),db=getFirestore(app),storage=getStorage(app),$=id=>document.getElementById(id),fallback='https://i.pravatar.cc/150?img=12';
let me=null;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const notify=text=>{const e=$('toast');if(!e)return;e.textContent=text;e.style.display='block';clearTimeout(window.__vibeActionToast);window.__vibeActionToast=setTimeout(()=>e.style.display='none',2800)};
const mainPanel=(html,title='VIBE',subtitle='Messagerie intelligente')=>{const messages=$('messages');if(!messages)return false;document.querySelector('.app')?.classList.add('chat-open');if($('name'))$('name').textContent=title;if($('status'))$('status').textContent=subtitle;if($('avatar'))$('avatar').src=me?.photoURL||fallback;if($('typing'))$('typing').hidden=true;if($('composer'))$('composer').hidden=true;messages.replaceChildren();const wrap=document.createElement('div');wrap.className='vibe-right-panel';wrap.innerHTML=html;messages.appendChild(wrap);messages.scrollTop=0;return true};
const restoreMain=()=>{const messages=$('messages');if(!messages)return;messages.innerHTML='<div class="welcome"><b>V</b><h2>VIBE</h2><p>Connecte-toi puis sélectionne une personne pour discuter.</p><div class="welcome-features"><span>Temps réel</span><span>Sécurisé</span><span>VIBE AI</span></div></div>';document.querySelector('.app')?.classList.remove('chat-open');if($('name'))$('name').textContent='VIBE';if($('status'))$('status').textContent='Messagerie intelligente';if($('avatar'))$('avatar').src=me?.photoURL||fallback};
const show=(html,title='VIBE',subtitle='Messagerie intelligente')=>mainPanel(html,title,subtitle);
const close=()=>{if($('modal')?.open)$('modal').close();restoreMain()};
async function users(){const snap=await getDocs(query(collection(db,'users'),limit(100)));return snap.docs.map(d=>d.data()).filter(u=>u.uid&&u.uid!==me?.uid)}
async function createGroup(){if(!me)return notify('Connecte-toi pour créer un groupe.');try{const list=await users();show(`<div class="vibe-panel"><div class="vibe-panel-head"><div><span class="vibe-kicker">VIBE</span><h2>Créer un groupe</h2><p>Tout se fait dans VIBE, sans ouvrir une nouvelle page.</p></div><button type="button" class="vibe-x" data-action="close">×</button></div><label class="vibe-field"><span>Nom du groupe</span><input id="vibeGroupName" maxlength="60" placeholder="Nom du groupe"></label><div class="vibe-field"><span>Membres</span><div class="vibe-members">${list.map(u=>`<label><input type="checkbox" value="${esc(u.uid)}"><img src="${esc(u.avatar||fallback)}" alt=""><span>${esc(u.name||'Utilisateur')}</span></label>`).join('')||'<small>Aucun autre utilisateur disponible.</small>'}</div></div><div class="vibe-panel-actions"><button type="button" class="vibe-secondary" data-action="close">Annuler</button><button type="button" class="vibe-primary" data-action="save-group">Créer le groupe</button></div></div>`)}catch(e){notify('Impossible de charger les membres : '+(e?.message||'erreur'))}}
async function saveGroup(){const name=$('vibeGroupName')?.value.trim(),ids=[...document.querySelectorAll('.vibe-members input:checked')].map(x=>x.value);if(!name)return notify('Donne un nom au groupe.');if(!ids.length)return notify('Choisis au moins un membre.');try{const participants=[...new Set([me.uid,...ids.filter(id=>id!==me.uid)])],group={name,participants,createdBy:me.uid,avatar:fallback,createdAt:serverTimestamp(),updatedAt:serverTimestamp()},refDoc=await addDoc(collection(db,'groups'),group);close();notify('Groupe créé.');const open={id:refDoc.id,name,participants,avatar:fallback,group:true};if(window.VIBE_OPEN_GROUP)window.VIBE_OPEN_GROUP(open);else{const openIt=()=>{const el=document.querySelector(`.contact[data-id="${CSS.escape(refDoc.id)}"]`);if(el){el.click();return true}return false};if(!openIt()){let n=0;const timer=setInterval(()=>{if(openIt()||++n>20)clearInterval(timer)},250)}}}catch(e){notify('Création impossible : '+(e?.message||'erreur'))}}
function createStatus(){if(!me)return notify('Connecte-toi pour publier un statut.');show(`<div class="vibe-panel"><div class="vibe-panel-head"><div><span class="vibe-kicker">VIBE</span><h2>Nouveau statut</h2><p>Publie une actualité sans quitter l'application.</p></div><button type="button" class="vibe-x" data-action="close">×</button></div><label class="vibe-field"><span>Ton statut</span><textarea id="vibeStatusText" maxlength="700" rows="5" placeholder="Quoi de neuf ?"></textarea></label><label class="vibe-upload"><span>Ajouter une photo ou une vidéo (facultatif)</span><input id="vibeStatusFile" type="file" accept="image/*,video/*"></label><div class="vibe-preview" id="vibeStatusPreview"></div><div class="vibe-panel-actions"><button type="button" class="vibe-secondary" data-action="close">Annuler</button><button type="button" class="vibe-primary" data-action="save-status">Publier</button></div></div>`,'Nouveau statut','Publie dans VIBE');$('vibeStatusFile')?.addEventListener('change',e=>{const f=e.target.files?.[0],p=$('vibeStatusPreview');if(!f||!p)return;p.textContent=`${f.name} · ${(f.size/1024/1024).toFixed(1)} Mo`})}
async function saveStatus(){const text=$('vibeStatusText')?.value.trim(),file=$('vibeStatusFile')?.files?.[0];if(!text&&!file)return notify('Ajoute un texte ou une photo/vidéo.');if(file&&file.size>25*1024*1024)return notify('Fichier limité à 25 Mo.');try{let mediaURL='',mediaType='';if(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,100),snap=await uploadBytes(ref(storage,`status-media/${me.uid}/${Date.now()}_${safe}`),file,{contentType:file.type||'application/octet-stream'});mediaURL=await getDownloadURL(snap.ref);mediaType=file.type||''}await addDoc(collection(db,'stories'),{uid:me.uid,text:(text||'').slice(0,700),mediaURL,mediaType,createdAt:serverTimestamp(),expiresAt:new Date(Date.now()+24*60*60*1000)});close();notify('Statut publié pendant 24 h.')}catch(e){notify('Publication impossible : '+(e?.message||'erreur'))}}
function showStories(){document.querySelectorAll('.rail-button').forEach(b=>b.classList.toggle('active',b.id==='railStories'));const contacts=$('contacts'),stories=$('stories');if(contacts)contacts.hidden=true;if(stories)stories.hidden=false;document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.tab==='stories'));if(stories?.children.length===0)notify('Chargement des statuts…')}
function showCommunities(){show(`<div class="vibe-panel"><div class="vibe-panel-head"><div><span class="vibe-kicker">VIBE</span><h2>Communautés</h2><p>Les espaces communautaires restent intégrés à VIBE.</p></div><button type="button" class="vibe-x" data-action="close">×</button></div><div class="vibe-empty-panel"><i class="fa-solid fa-users"></i><b>Créer une communauté</b><span>Cette section reste dans VIBE et n'ouvre pas Chrome.</span><button type="button" class="vibe-primary" data-action="create-group">Créer un groupe</button></div></div>`,'Communautés','Espaces VIBE')}
function profile(){show(`<div class="vibe-panel"><div class="vibe-panel-head"><div><span class="vibe-kicker">MON COMPTE</span><h2>${esc(me?.displayName||me?.email?.split('@')[0]||'Utilisateur')}</h2><p>${esc(me?.email||'')}</p></div><button type="button" class="vibe-x" data-action="close">×</button></div><div class="vibe-profile-card"><img src="${esc(me?.photoURL||fallback)}" alt=""><div><b>Profil VIBE</b><span>Compte connecté</span></div></div></div>`,'Mon profil','Compte VIBE')}
function settings(){show(`<div class="vibe-panel"><div class="vibe-panel-head"><div><span class="vibe-kicker">VIBE</span><h2>Paramètres</h2><p>Les réglages restent dans l'application.</p></div><button type="button" class="vibe-x" data-action="close">×</button></div><div class="vibe-settings"><button type="button" data-action="theme"><i class="fa-solid fa-circle-half-stroke"></i><span>Changer le thème</span></button><button type="button" data-action="close"><i class="fa-solid fa-check"></i><span>Fermer</span></button></div></div>`,'Paramètres','Réglages VIBE')}
function action(event){const a=event.target.closest?.('[data-action]');if(!a)return;event.preventDefault();event.stopPropagation();const x=a.dataset.action;if(x==='close')close();else if(x==='save-group')saveGroup();else if(x==='save-status')saveStatus();else if(x==='create-group')createGroup();else if(x==='theme'){document.body.classList.toggle('dark');localStorage.setItem('vibe-dark',document.body.classList.contains('dark')?'1':'0')}}
function bind(){const map={newGroup:createGroup,newGroupQuick:createGroup,newStatusQuick:createStatus,railStories:showStories,railCommunities:showCommunities,railProfile:profile,profile,railSettings:settings};Object.entries(map).forEach(([id,fn])=>$(id)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn()},true));document.addEventListener('click',action,true);document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',e=>{if(t.dataset.tab==='stories'){e.preventDefault();e.stopImmediatePropagation();showStories()}},true));if(localStorage.getItem('vibe-dark')==='1')document.body.classList.add('dark')}
onAuthStateChanged(auth,u=>{me=u||null});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();