import { getApps } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getDatabase, ref, push, set, update, remove, get, onValue, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js';
const app=getApps()[0]; if(!app) throw new Error('Firebase doit être initialisé avant vibe-fixes.js');
const auth=getAuth(app),db=getDatabase(app,'https://vibe-749e5-default-rtdb.firebaseio.com');
const $=s=>document.querySelector(s); let user=null,selected=null,stopReactions=null,stopPeerPresence=null; const consumed=new Set();
function toast(message){const el=$('#toast');if(!el)return;el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2800)}
function currentChatId(){return window.VibeApp?.currentChatId||document.querySelector('.conversation-item.active')?.dataset.chatId||selected}
function cleanup(){stopReactions?.();stopPeerPresence?.();stopReactions=stopPeerPresence=null}
function makeId(){return `chat-${Date.now().toString(36)}-${crypto.randomUUID().slice(0,8)}`}
function makeInviteToken(){return crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','')}
function clean(v,max=2000){return String(v||'').trim().slice(0,max)}
async function createPrivateChat(){if(!user)return toast('Connexion Firebase requise.');const name=clean(prompt('Nom de la discussion :'),120);if(!name)return;const id=makeId(),token=makeInviteToken();try{await update(ref(db),{[`chats/${id}`]:{name,ownerUid:user.uid,createdAt:serverTimestamp(),inviteToken:token},[`chatMembers/${id}/${user.uid}`]:true,[`userChats/${user.uid}/${id}`]:true});toast(`Discussion créée. Code d’invitation : ${token}`);window.VibeApp?.openChat(id,{name,ownerUid:user.uid,inviteToken:token})}catch(e){toast(`Création impossible : ${e.message}`)}}
async function joinPrivateChat(){if(!user)return toast('Connexion Firebase requise.');const id=clean(prompt('Identifiant de la discussion :'),120);if(!id)return;const token=clean(prompt('Code d’invitation privé :'),128);if(!token)return;try{const snap=await get(ref(db,`chats/${id}`));if(!snap.exists())return toast('Discussion introuvable.');const chat=snap.val();if(chat.ownerUid!==user.uid&&chat.inviteToken!==token)return toast('Code d’invitation invalide.');await set(ref(db,`joinRequests/${id}/${user.uid}`),true);await update(ref(db),{[`chatMembers/${id}/${user.uid}`]:true,[`userChats/${user.uid}/${id}`]:true});toast('Accès privé autorisé.');window.VibeApp?.openChat(id,chat)}catch(e){toast(`Impossible de rejoindre : ${e.message}`)}}
async function atomicSend(text,type='text',extra={}){const chatId=currentChatId();if(!chatId||!user||!text)return false;const key=push(ref(db,`messages/${chatId}`)).key;if(!key)return false;const message={text:clean(text,20000),uid:user.uid,createdAt:serverTimestamp(),type,viewOnce:Boolean(extra.viewOnce),...extra};await update(ref(db),{[`messages/${chatId}/${key}`]:message,[`events/${user.uid}/${key}`]:{type:'message_sent',chatId,messageId:key,createdAt:serverTimestamp()}});return true}
async function handleSubmit(e){if(e.target!==$('#messageForm'))return;e.preventDefault();e.stopImmediatePropagation();const input=$('#messageInput'),text=clean(input?.value);if(!text)return;try{if(await atomicSend(text)){input.value='';toast('Message envoyé.')}}catch(err){toast(`Impossible d'envoyer : ${err.message}`)}}
function handleAttachment(e){if(e.target?.id!=='attachBtn')return;e.preventDefault();e.stopImmediatePropagation();$('#fileInput')?.click()}
async function handleFile(e){if(e.target?.id!=='fileInput')return;const file=e.target.files?.[0];e.target.value='';if(!file)return;const allowed=file.type.startsWith('image/')||file.type.startsWith('video/')||file.type.startsWith('audio/')||file.type==='application/pdf';if(!allowed)return toast('Type de fichier non pris en charge.');if(file.size>750*1024)return toast('Fichier trop volumineux : 750 Ko maximum.');if(!currentChatId()||!user)return toast('Ouvrez une discussion.');try{const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});await atomicSend(file.name,'media',{fileName:file.name.slice(0,180),mimeType:file.type,dataUrl});toast('Fichier envoyé.')}catch(err){toast(`Envoi impossible : ${err.message}`)}}
function decorateReactions(raw){const map={};for(const [mid,users] of Object.entries(raw||{})){const c={};for(const v of Object.values(users||{}))c[v]=(c[v]||0)+1;map[mid]=Object.entries(c).map(([e,n])=>e+(n>1?` ${n}`:'')).join(' ')}document.querySelectorAll('#messages [data-message]').forEach(el=>{el.querySelector('.message-reaction')?.remove();if(map[el.dataset.message]){const b=document.createElement('span');b.className='message-reaction';b.textContent=map[el.dataset.message];el.appendChild(b)}})}
function watchReactions(id){stopReactions?.();stopReactions=onValue(ref(db,`reactions/${id}`),s=>decorateReactions(s.val()||{}))}
async function watchPresence(id){stopPeerPresence?.();const members=(await get(ref(db,`chatMembers/${id}`))).val()||{},peers=Object.keys(members).filter(x=>x!==user?.uid),el=$('#chatPresence');if(!peers.length){if(el)el.textContent='vous êtes le seul membre';return}const states=new Map(),listeners=[];const paint=()=>{const n=[...states.values()].filter(v=>v==='online').length;if(el)el.textContent=peers.length===1?(n?'en ligne':'hors ligne'):`${n}/${peers.length} en ligne`};for(const id of peers)listeners.push(onValue(ref(db,`presence/${id}/status`),s=>{states.set(id,s.val()?.state||'offline');paint()}));stopPeerPresence=()=>listeners.forEach(fn=>fn())}
function viewOnceClick(e){const el=e.target.closest('#messages [data-message]');if(!el||!user)return;const id=el.dataset.message,chatId=currentChatId();if(!id||consumed.has(id)||!chatId)return;get(ref(db,`messages/${chatId}/${id}`)).then(async s=>{const m=s.val();if(!m?.viewOnce||m.uid===user.uid)return;consumed.add(id);try{await remove(ref(db,`messages/${chatId}/${id}`));toast('Message à vue unique consommé.')}catch(err){consumed.delete(id);toast(`Impossible : ${err.message}`)}})}
async function cleanupStories(){if(!user)return;const raw=(await get(ref(db,`stories/${user.uid}`))).val()||{},now=Date.now();await Promise.all(Object.entries(raw).filter(([,s])=>Number(s?.expiresAt||0)<=now).map(([id])=>remove(ref(db,`stories/${user.uid}/${id}`)).catch(()=>{})))}
function monitor(){const id=currentChatId();if(!id||id===selected){if(!id)cleanup();return}selected=id;cleanup();watchReactions(id);watchPresence(id).catch(()=>{})}
onAuthStateChanged(auth,async u=>{user=u;if(u)await cleanupStories().catch(()=>{});selected=null;monitor();document.dispatchEvent(new CustomEvent('vibe:auth-changed',{detail:{user:u}}))});
document.addEventListener('click',e=>{const target=e.target.closest('#newChatBtn,#menuBtn,#chatMenuBtn');if(target?.id==='newChatBtn'){e.preventDefault();e.stopImmediatePropagation();createPrivateChat();return}if(target?.id==='chatMenuBtn'){e.preventDefault();e.stopImmediatePropagation();const choice=prompt('Vibe :\n1. Rejoindre une discussion privée\n2. Message à vue unique\n3. Réagir au dernier message');if(choice==='1')joinPrivateChat();else if(choice==='2')atomicSend(clean(prompt('Message à vue unique :')), 'text',{viewOnce:true}).then(ok=>ok&&toast('Message à vue unique envoyé.'));else if(choice==='3'){const id=currentChatId();if(!id||!user)return;get(ref(db,`messages/${id}`)).then(s=>{const last=Object.keys(s.val()||{}).at(-1);if(!last)return;const reaction=clean(prompt('Réaction : ❤️ 👍 😂 😮 😢 🙏'),16);if(reaction)set(ref(db,`reactions/${id}/${last}/${user.uid}`),reaction).then(()=>toast('Réaction enregistrée.'))})}return}if(e.target.closest('[data-chat-id]'))setTimeout(monitor,0);viewOnceClick(e)},true);
document.addEventListener('submit',handleSubmit,true);document.addEventListener('click',handleAttachment,true);document.addEventListener('change',handleFile,true);
window.VibeFixes={createPrivateChat,joinPrivateChat};
