import { auth, db, onAuthStateChanged, doc, collection, setDoc, updateDoc, getDoc, deleteDoc, onSnapshot, addDoc } from './firebase-client.js';

let user=null,pc=null,localStream=null,callId=null,stopCall=null,stopCallCandidates=null,stopIncoming=null,remoteUid=null,remoteDescriptionReady=false,endingCall=false,startPending=false,callKind=null,callChatId=null;const pendingCandidates=[];const $=s=>document.querySelector(s);
function activeChatId(){return document.querySelector('.conversation-item.active')?.dataset.chatId||document.querySelector('.conversation.active')?.dataset.chat||window.VibeApp?.currentChatId||null}
function toast(text){const e=$('#toast');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function peerUid(id){return getDoc(doc(db,'conversations',id)).then(s=>(s.data()?.participantIds||[]).find(x=>x!==user?.uid)||null)}
function ensurePanel(video){let p=document.querySelector('#vibeCallPanel');if(p){const r=$('#vibeRemoteVideo');if(r)r.style.display=video?'block':'none';return p}p=document.createElement('div');p.id='vibeCallPanel';p.style='position:fixed;inset:18px;z-index:10000;background:rgba(12,12,16,.96);border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:18px;display:flex;flex-direction:column;gap:12px;color:#fff;font-family:inherit;box-shadow:0 25px 80px rgba(0,0,0,.5)';p.innerHTML=`<div id="vibeCallState">Connexion…</div><video id="vibeRemoteVideo" autoplay playsinline style="width:100%;height:100%;max-height:70vh;object-fit:contain;border-radius:14px;background:#08080a"></video><div style="display:flex;justify-content:center;gap:10px"><button id="vibeHangup" type="button">Raccrocher</button></div>`;document.body.appendChild(p);if(!video)$('#vibeRemoteVideo').style.display='none';$('#vibeHangup').addEventListener('click',()=>endCall());return p}
function setState(text){const e=$('#vibeCallState');if(e)e.textContent=text}
async function flushPendingCandidates(){if(!pc||!remoteDescriptionReady)return;while(pendingCandidates.length){const c=pendingCandidates.shift();try{await pc.addIceCandidate(c)}catch(e){console.warn('ICE:',e)}}}
function watchCandidates(id,remote){return onSnapshot(collection(db,'calls',id,'candidates',remote),s=>{for(const item of s.docChanges()){if(item.type!=='added'||!pc)continue;const c=item.doc.data();const rtc=new RTCIceCandidate(c);if(remoteDescriptionReady)pc.addIceCandidate(rtc).catch(()=>{});else pendingCandidates.push(rtc)}})}
async function setupPeer(id,isCaller,kind){if(!navigator.mediaDevices?.getUserMedia)throw new Error('La caméra et le microphone ne sont pas disponibles.');pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.google.com:19302'}]});pc.onconnectionstatechange=()=>{if(!pc||endingCall)return;if(pc.connectionState==='connected')setState('Appel connecté.');if(pc.connectionState==='failed'){setState('Connexion échouée.');toast('La connexion WebRTC a échoué.');void endCall()}};pc.ontrack=e=>{const r=$('#vibeRemoteVideo');if(r){r.style.display=kind==='video'?'block':'none';if(e.streams?.[0])r.srcObject=e.streams[0]}};pc.onicecandidate=e=>{if(!e.candidate||!callId||!user||endingCall)return;addDoc(collection(db,'calls',callId,'candidates',user.uid),e.candidate.toJSON()).catch(()=>{})};localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));if(isCaller){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await updateDoc(doc(db,'calls',id),{offer:{type:offer.type,sdp:offer.sdp}})}else{const s=await getDoc(doc(db,'calls',id)),c=s.data();if(!c?.offer)throw new Error('Offre WebRTC absente.');await pc.setRemoteDescription(c.offer);remoteDescriptionReady=true;await flushPendingCandidates();const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await updateDoc(doc(db,'calls',id),{answer:{type:answer.type,sdp:answer.sdp},status:'accepted'})}return pc}
async function writeCallHistory(call,status){if(!call)return;const peers=[call.callerUid,call.calleeUid];const base={callId:call.id||callId,chatId:call.chatId,kind:call.kind,status,createdAt:call.createdAt||null,endedAt:new Date()};for(const uid of peers){if(!uid)continue;const peer=uid===call.callerUid?call.calleeUid:call.callerUid;await setDoc(doc(db,'callHistory',uid,'items',`${base.callId}_${uid}`),{...base,uid,peerUid:peer},{merge:true}).catch(()=>{})}}
async function startCall(kind){if(startPending)return;startPending=true;try{if(!user)return toast('Connexion requise.');if(callId||pc||endingCall)return toast('Un appel est déjà en cours.');const id=activeChatId();if(!id||id.startsWith('demo-'))return toast('Ouvrez une discussion synchronisée.');let callee;try{callee=await peerUid(id)}catch(e){return toast(`Impossible de trouver le contact : ${e.message}`)}if(!callee)return toast('Aucun autre membre dans cette discussion.');callId=doc(collection(db,'calls')).id;remoteUid=callee;callKind=kind;callChatId=id;remoteDescriptionReady=false;pendingCandidates.length=0;ensurePanel(kind==='video');setState(`Appel ${kind==='video'?'vidéo':'audio'} vers le contact…`);try{await setDoc(doc(db,'calls',callId),{callerUid:user.uid,calleeUid:callee,chatId:id,kind,status:'ringing',createdAt:new Date()});await setupPeer(callId,true,kind);await setDoc(doc(db,'incomingCalls',callee,'calls',callId),{callerUid:user.uid,calleeUid:callee,chatId:id,kind,createdAt:new Date()});stopCall=onSnapshot(doc(db,'calls',callId),async s=>{const c=s.data()||{};if(c.status==='ended'||c.status==='rejected'){await endCall(false,{id:callId,...c});return}if(c.answer&&pc&&!pc.currentRemoteDescription&&!endingCall)try{await pc.setRemoteDescription(c.answer);remoteDescriptionReady=true;await flushPendingCandidates();setState('Appel connecté.')}catch(e){console.warn('Réponse WebRTC:',e)}});stopCallCandidates=watchCandidates(callId,callee);setState('Appel en attente…')}catch(e){toast(`Appel impossible : ${e.message}`);await endCall()}}finally{startPending=false}}
async function acceptIncoming(id,kind){if(!user||callId||pc||endingCall)return;callId=id;callKind=kind;remoteDescriptionReady=false;pendingCandidates.length=0;ensurePanel(kind==='video');setState('Connexion à l’appel…');try{const s=await getDoc(doc(db,'calls',id)),c=s.data();if(!c||c.calleeUid!==user.uid||c.status==='ended'){await endCall(false,c);return}remoteUid=c.callerUid;callChatId=c.chatId;await setupPeer(id,false,kind);stopCallCandidates=watchCandidates(id,c.callerUid);stopCall=onSnapshot(doc(db,'calls',id),s2=>{const c2=s2.data();if(!c2||c2.status==='ended'||c2.status==='rejected')void endCall(false,c2)});await deleteDoc(doc(db,'incomingCalls',user.uid,'calls',id)).catch(()=>{});setState('Appel connecté.')}catch(e){toast(`Appel impossible : ${e.message}`);await endCall()}}
async function endCall(writeEnded=true,knownCall=null){if(endingCall)return;endingCall=true;const currentCallId=callId,currentUser=user,currentRemoteUid=remoteUid;let call=knownCall;if(!call&&currentCallId){try{const s=await getDoc(doc(db,'calls',currentCallId));if(s.exists())call={id:currentCallId,...s.data()}}catch{}}if(call&&writeEnded){await updateDoc(doc(db,'calls',currentCallId),{status:'ended',endedAt:new Date()}).catch(()=>{});call={...call,status:'ended'}}if(call)await writeCallHistory(call,call.status||'ended');stopCall?.();stopCallCandidates?.();stopCall=stopCallCandidates=null;if(currentUser&&currentCallId)await deleteDoc(doc(db,'incomingCalls',currentUser.uid,'calls',currentCallId)).catch(()=>{});if(currentRemoteUid&&currentCallId)await deleteDoc(doc(db,'incomingCalls',currentRemoteUid,'calls',currentCallId)).catch(()=>{});localStream?.getTracks().forEach(t=>t.stop());pc?.close();pc=null;localStream=null;callId=null;remoteUid=null;callKind=null;callChatId=null;remoteDescriptionReady=false;pendingCandidates.length=0;document.querySelector('#vibeCallPanel')?.remove();endingCall=false}
function watchIncoming(){if(!user)return;stopIncoming?.();const q=collection(db,'incomingCalls',user.uid,'calls');stopIncoming=onSnapshot(q,async s=>{for(const change of s.docChanges()){if(change.type!=='added'||document.querySelector('#vibeCallPanel')||callId||endingCall)continue;const c=change.doc.data();const ok=confirm(`Appel ${c.kind==='video'?'vidéo':'audio'} entrant. Accepter ?`);if(ok)await acceptIncoming(change.doc.id,c.kind);else{await deleteDoc(change.doc.ref).catch(()=>{});await writeCallHistory({id:change.doc.id,...c},'rejected')}}})}
onAuthStateChanged(auth,current=>{user=current;if(!user){stopIncoming?.();stopIncoming=null;void endCall(false);return}watchIncoming()});
document.addEventListener('click',e=>{const b=e.target.closest('.chat-actions .glass-btn');if(!b||b.id==='chatMenuBtn')return;e.preventDefault();e.stopImmediatePropagation();const kind=b.title==='Appel vidéo'?'video':'audio';setTimeout(()=>void startCall(kind),0)},true);
