import { getApps } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getDatabase, ref, get, set, update, remove, onValue, push, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js';
const app=getApps()[0];
if(!app)throw new Error('Firebase doit être initialisé avant webrtc-calls.js');
const auth=getAuth(app),db=getDatabase(app,'https://vibe-749e5-default-rtdb.firebaseio.com');
let user=null,pc=null,localStream=null,callId=null,stopCall=null,stopCallCandidates=null,stopIncoming=null,remoteUid=null,remoteDescriptionReady=false,endingCall=false;
const pendingCandidates=[];const $=s=>document.querySelector(s);
function activeChatId(){return document.querySelector('.conversation.active')?.dataset.chat||null}
function toast(text){const e=$('#toast');if(!e)return;e.textContent=text;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function peerUid(id){return get(ref(db,`chatMembers/${id}`)).then(s=>Object.keys(s.val()||{}).find(x=>x!==user?.uid)||null)}
function ensurePanel(video){let p=document.querySelector('#vibeCallPanel');if(p){const r=$('#vibeRemoteVideo');if(r)r.style.display=video?'block':'none';return p}p=document.createElement('div');p.id='vibeCallPanel';p.style='position:fixed;inset:18px;z-index:10000;background:rgba(12,12,16,.96);border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:18px;display:flex;flex-direction:column;gap:12px;color:#fff;font-family:inherit;box-shadow:0 25px 80px rgba(0,0,0,.5)';p.innerHTML=`<div id="vibeCallState">Connexion…</div><video id="vibeRemoteVideo" autoplay playsinline style="width:100%;height:100%;max-height:70vh;object-fit:contain;border-radius:14px;background:#08080a"></video><div style="display:flex;justify-content:center;gap:10px"><button id="vibeHangup" type="button">Raccrocher</button></div>`;document.body.appendChild(p);if(!video)$('#vibeRemoteVideo').style.display='none';$('#vibeHangup').addEventListener('click',()=>endCall());return p}
function setState(text){const e=$('#vibeCallState');if(e)e.textContent=text}
async function flushPendingCandidates(){if(!pc||!remoteDescriptionReady)return;while(pendingCandidates.length){const c=pendingCandidates.shift();try{await pc.addIceCandidate(c)}catch(e){console.warn('ICE candidate ignoré:',e)}}}
function watchCandidates(id,remoteUidToWatch){return onValue(ref(db,`calls/${id}/candidates/${remoteUidToWatch}`),s=>{for(const c of Object.values(s.val()||{})){if(!c||!pc)continue;const rtc=new RTCIceCandidate(c);if(remoteDescriptionReady)pc.addIceCandidate(rtc).catch(e=>console.warn('ICE:',e));else pendingCandidates.push(rtc)}})}
async function setupPeer(id,isCaller,kind){if(!navigator.mediaDevices?.getUserMedia)throw new Error('La caméra et le microphone ne sont pas disponibles dans ce navigateur.');pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});pc.onconnectionstatechange=()=>{if(!pc||endingCall)return;if(pc.connectionState==='connected')setState('Appel connecté.');if(pc.connectionState==='disconnected')setState('Connexion interrompue…');if(pc.connectionState==='failed'){setState('Connexion échouée.');toast('La connexion WebRTC a échoué.');endCall()}};pc.oniceconnectionstatechange=()=>{if(!pc||endingCall)return;if(pc.iceConnectionState==='failed')toast('Connexion réseau de l’appel impossible.')};pc.ontrack=e=>{const r=$('#vibeRemoteVideo');if(!r)return;r.style.display=kind==='video'?'block':'none';if(e.streams?.[0])r.srcObject=e.streams[0]};pc.onicecandidate=e=>{if(!e.candidate||!callId||!user||endingCall)return;const r=push(ref(db,`calls/${callId}/candidates/${user.uid}`));set(r,e.candidate.toJSON()).catch(err=>console.warn('Publication ICE:',err))};localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));if(isCaller){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await update(ref(db,`calls/${id}`),{offer:{type:offer.type,sdp:offer.sdp}})}else{const s=await get(ref(db,`calls/${id}`)),c=s.val();if(!c?.offer)throw new Error('Offre WebRTC absente.');await pc.setRemoteDescription(c.offer);remoteDescriptionReady=true;await flushPendingCandidates();const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await update(ref(db,`calls/${id}`),{answer:{type:answer.type,sdp:answer.sdp},status:'accepted'})}return pc}
async function startCall(kind){if(!user)return toast('Connexion requise.');if(callId||pc||endingCall)return toast('Un appel est déjà en cours.');const id=activeChatId();if(!id||id.startsWith('demo-'))return toast('Ouvrez une discussion synchronisée.');let callee;try{callee=await peerUid(id)}catch(e){return toast(`Impossible de trouver le contact : ${e.message}`)}if(!callee)return toast('Aucun autre membre dans cette discussion.');callId=push(ref(db,'calls')).key;remoteUid=callee;remoteDescriptionReady=false;pendingCandidates.length=0;ensurePanel(kind==='video');setState(`Appel ${kind==='video'?'vidéo':'audio'} vers le contact…`);try{await set(ref(db,`calls/${callId}`),{callerUid:user.uid,calleeUid:callee,chatId:id,kind,status:'ringing',createdAt:serverTimestamp()});await setupPeer(callId,true,kind);await set(ref(db,`incomingCalls/${callee}/${callId}`),{callerUid:user.uid,chatId:id,kind,createdAt:serverTimestamp()});stopCall=onValue(ref(db,`calls/${callId}`),async s=>{const c=s.val()||{};if(c.status==='ended'||c.status==='rejected'){await endCall(false);return}if(c.answer&&pc&&!pc.currentRemoteDescription&&!endingCall)try{await pc.setRemoteDescription(c.answer);remoteDescriptionReady=true;await flushPendingCandidates();setState('Appel connecté.')}catch(e){console.warn('Réponse WebRTC:',e)}});stopCallCandidates=watchCandidates(callId,callee);setState('Appel en attente…')}catch(e){toast(`Appel impossible : ${e.message}`);await endCall()}}
async function acceptIncoming(id,kind){if(!user||callId||pc||endingCall)return;callId=id;remoteDescriptionReady=false;pendingCandidates.length=0;ensurePanel(kind==='video');setState('Connexion à l’appel…');try{const s=await get(ref(db,`calls/${id}`)),c=s.val();if(!c||c.calleeUid!==user.uid||c.status==='ended'){await endCall(false);return}remoteUid=c.callerUid;await setupPeer(id,false,kind);stopCallCandidates=watchCandidates(id,c.callerUid);stopCall=onValue(ref(db,`calls/${id}`),s2=>{const c2=s2.val();if(!c2||c2.status==='ended'||c2.status==='rejected')endCall(false)});await remove(ref(db,`incomingCalls/${user.uid}/${id}`));setState('Appel connecté.')}catch(e){toast(`Appel impossible : ${e.message}`);await endCall()}}
async function endCall(writeEnded=true){if(endingCall)return;endingCall=true;const currentCallId=callId,currentUser=user,currentRemoteUid=remoteUid;if(stopCall)stopCall();if(stopCallCandidates)stopCallCandidates();stopCall=stopCallCandidates=null;if(writeEnded&&currentCallId&&currentUser){try{await update(ref(db,`calls/${currentCallId}`),{status:'ended',endedAt:serverTimestamp()})}catch(e){console.warn('Fin d’appel:',e)}try{await remove(ref(db,`incomingCalls/${currentUser.uid}/${currentCallId}`))}catch{}if(currentRemoteUid)try{await remove(ref(db,`incomingCalls/${currentRemoteUid}/${currentCallId}`))}catch{}}if(localStream)localStream.getTracks().forEach(t=>t.stop());const connection=pc;pc=null;if(connection)connection.close();localStream=null;callId=null;remoteUid=null;remoteDescriptionReady=false;pendingCandidates.length=0;document.querySelector('#vibeCallPanel')?.remove();endingCall=false}
function watchIncoming(){if(!user)return;if(stopIncoming)stopIncoming();stopIncoming=onValue(ref(db,`incomingCalls/${user.uid}`),async s=>{for(const[id,c]of Object.entries(s.val()||{})){if(!c||document.querySelector('#vibeCallPanel')||callId||endingCall)continue;const ok=confirm(`Appel ${c.kind==='video'?'vidéo':'audio'} entrant. Accepter ?`);if(ok)await acceptIncoming(id,c.kind);else await remove(ref(db,`incomingCalls/${user.uid}/${id}`))}})}
onAuthStateChanged(auth,current=>{user=current;if(!user){if(stopIncoming)stopIncoming();stopIncoming=null;endCall(false);return}watchIncoming()});
document.addEventListener('click',e=>{const b=e.target.closest('.chat-actions .glass-btn');if(!b||b.id==='chatMenuBtn')return;e.preventDefault();e.stopImmediatePropagation();startCall(b.title==='Appel vidéo'?'video':'audio')},true);
