import { getApps } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getDatabase, ref, get, set, update, remove, onValue, push, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-database.js';
const app=getApps()[0];if(!app)throw new Error('Firebase doit être initialisé avant webrtc-calls.js');
const auth=getAuth(app),db=getDatabase(app,'https://vibe-749e5-default-rtdb.firebaseio.com');
let user=null,pc=null,localStream=null,callId=null,stopCall=null,stopIncoming=null;const $=s=>document.querySelector(s);
function chatId(){return document.querySelector('.conversation.active')?.dataset.chat||null}
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2800)}
function peerUid(id){return get(ref(db,`chatMembers/${id}`)).then(s=>Object.keys(s.val()||{}).find(x=>x!==user?.uid)||null)}
function panel(video){let p=document.querySelector('#vibeCallPanel');if(p)return p;p=document.createElement('div');p.id='vibeCallPanel';p.style='position:fixed;inset:18px;z-index:10000;background:rgba(12,12,16,.96);border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:18px;display:flex;flex-direction:column;gap:12px;color:#fff;font-family:inherit;box-shadow:0 25px 80px rgba(0,0,0,.5)';p.innerHTML=`<div id="vibeCallState">Connexion…</div><video id="vibeRemoteVideo" autoplay playsinline style="width:100%;height:100%;max-height:70vh;object-fit:contain;border-radius:14px;background:#08080a"></video><div style="display:flex;justify-content:center;gap:10px"><button id="vibeHangup" type="button">Raccrocher</button></div>`;document.body.appendChild(p);if(!video)$('#vibeRemoteVideo').style.display='none';$('#vibeHangup').onclick=endCall;return p}
function setState(t){const e=$('#vibeCallState');if(e)e.textContent=t}
async function setupPeer(id,isCaller,calleeUid,kind){pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:kind==='video'});localStream.getTracks().forEach(t=>pc.addTrack(t,localStream));const remote=$('#vibeRemoteVideo');pc.ontrack=e=>{remote.style.display='block';remote.srcObject=e.streams[0]};pc.onicecandidate=e=>{if(e.candidate&&callId){const r=push(ref(db,`calls/${callId}/candidates/${user.uid}`));set(r,e.candidate.toJSON())}};if(isCaller){const offer=await pc.createOffer();await pc.setLocalDescription(offer);await update(ref(db,`calls/${id}`),{offer:{type:offer.type,sdp:offer.sdp}})}else{const snap=await get(ref(db,`calls/${id}`)),c=snap.val();if(!c?.offer)throw new Error('Offre WebRTC absente');await pc.setRemoteDescription(c.offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await update(ref(db,`calls/${id}`),{answer:{type:answer.type,sdp:answer.sdp},status:'accepted'})}return pc}
function watchCandidates(id,remoteUid){return onValue(ref(db,`calls/${id}/candidates/${remoteUid}`),snap=>{for(const c of Object.values(snap.val()||{}))pc?.addIceCandidate(new RTCIceCandidate(c)).catch(()=>{})})}
async function startCall(kind){if(!user)return toast('Connexion requise.');const id=chatId();if(!id||id.startsWith('demo-'))return toast('Ouvrez une discussion synchronisée.');const callee=await peerUid(id);if(!callee)return toast('Aucun autre membre dans cette discussion.');callId=push(ref(db,'calls')).key;panel(kind==='video');setState(`Appel ${kind==='video'?'vidéo':'audio'} vers le contact…`);try{await set(ref(db,`calls/${callId}`),{callerUid:user.uid,calleeUid:callee,chatId:id,kind,status:'ringing',createdAt:serverTimestamp()});await setupPeer(callId,true,callee,kind);await set(ref(db,`incomingCalls/${callee}/${callId}`),{callerUid:user.uid,chatId:id,kind,createdAt:serverTimestamp()});stopCall=onValue(ref(db,`calls/${callId}`),async snap=>{const c=snap.val()||{};if(c.answer&&pc&&!pc.currentRemoteDescription){await pc.setRemoteDescription(c.answer);setState('Appel connecté.')}});stopCallCandidates=watchCandidates(callId,callee);setState('Appel en attente…')}catch(e){toast(`Appel impossible : ${e.message}`);endCall()}}
async function acceptIncoming(id,kind){callId=id;panel(kind==='video');try{const snap=await get(ref(db,`calls/${id}`));const c=snap.val();if(!c||c.calleeUid!==user.uid)return;await setupPeer(id,false,c.callerUid,kind);stopCall=onValue(ref(db,`calls/${id}`),snap2=>{if(snap2.val()?.status==='ended')endCall()});stopCallCandidates=watchCandidates(id,c.callerUid);await remove(ref(db,`incomingCalls/${user.uid}/${id}`));setState('Appel connecté.')}catch(e){toast(`Appel impossible : ${e.message}`);endCall()}}
let stopCallCandidates=null;
async function endCall(){try{if(stopCall)stopCall();if(stopCallCandidates)stopCallCandidates();if(callId&&user){await update(ref(db,`calls/${callId}`),{status:'ended',endedAt:serverTimestamp()});await remove(ref(db,`incomingCalls/${user.uid}/${callId}`)).catch(()=>{})}}catch{}if(localStream)localStream.getTracks().forEach(t=>t.stop());if(pc)pc.close();pc=null;localStream=null;callId=null;stopCall=stopCallCandidates=null;document.querySelector('#vibeCallPanel')?.remove()}
async function incoming(){if(!user)return;if(stopIncoming)stopIncoming();stopIncoming=onValue(ref(db,`incomingCalls/${user.uid}`),async snap=>{for(const [id,c] of Object.entries(snap.val()||{})){if(document.querySelector('#vibeCallPanel'))continue;const ok=confirm(`Appel ${c.kind==='video'?'vidéo':'audio'} entrant. Accepter ?`);if(ok)await acceptIncoming(id,c.kind);else await remove(ref(db,`incomingCalls/${user.uid}/${id}`))}})}
onAuthStateChanged(auth,u=>{user=u;incoming()});
document.addEventListener('click',e=>{const b=e.target.closest('.chat-actions .glass-btn');if(!b||b.id==='chatMenuBtn')return;e.preventDefault();e.stopImmediatePropagation();startCall(b.title==='Appel vidéo'?'video':'audio')},true);
