import { auth, db, collection, addDoc, onSnapshot, serverTimestamp, storage, ref, uploadBytes, getDownloadURL } from './firebase-client.js';

const $ = id => document.getElementById(id);
let modal;
const userId = () => auth?.currentUser?.uid || null;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(t){const e=$('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
function openModal(title, body){modal?.remove();modal=document.createElement('div');modal.className='vibe-extra-modal';modal.innerHTML=`<div class="vibe-extra-card"><header><strong>${esc(title)}</strong><button type="button" aria-label="Fermer">×</button></header><div class="vibe-extra-body">${body}</div></div>`;document.body.appendChild(modal);modal.querySelector('header button').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()})}
async function uploadMedia(file, folder){const uid=userId();if(!uid)throw new Error('Connexion requise');if(file.size>25*1024*1024)throw new Error('Fichier limité à 25 Mo');const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const r=ref(storage,`${folder}/${uid}/${Date.now()}-${safe}`);await uploadBytes(r,file,{contentType:file.type});return getDownloadURL(r)}
async function publishStatus(){const uid=userId();if(!uid)return toast('Connectez-vous pour publier.');const text=$('vibeStatusText')?.value.trim();const file=$('vibeStatusFile')?.files?.[0];if(!text&&!file)return toast('Ajoutez un texte ou un média.');try{let mediaUrl='',mediaType='';if(file){mediaUrl=await uploadMedia(file,'statuses');mediaType=file.type}await addDoc(collection(db,'statuses'),{uid,text:text||'',mediaUrl,mediaType,createdAt:serverTimestamp(),expiresAt:new Date(Date.now()+86400000)});toast('Statut publié pour 24 h.');modal?.remove()}catch(e){toast(e.message)}}
function statusUI(){openModal('Statut / Actus 24 h','<textarea id="vibeStatusText" class="vibe-extra-input" maxlength="700" placeholder="Écrire un statut…"></textarea><input id="vibeStatusFile" class="vibe-extra-input" type="file" accept="image/*,video/*"><button class="vibe-extra-primary" id="vibePublishStatus">Publier</button><div id="vibeStatusList" class="vibe-extra-list">Chargement…</div>');$('vibePublishStatus').onclick=publishStatus;const q=collection(db,'statuses');onSnapshot(q,s=>{const now=Date.now();const rows=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!x.expiresAt?.toMillis||x.expiresAt.toMillis()>now).sort((a,b)=>(b.createdAt?.toMillis?.()||0)-(a.createdAt?.toMillis?.()||0)).slice(0,30);$('vibeStatusList').innerHTML=rows.length?rows.map(x=>`<article><strong>${esc(x.uid===userId()?'Vous':x.uid)}</strong><p>${esc(x.text)}</p>${x.mediaUrl?(x.mediaType?.startsWith('video/')?`<video controls src="${esc(x.mediaUrl)}"></video>`:`<img src="${esc(x.mediaUrl)}" alt="Statut">`):''}</article>`).join(''):'Aucun statut récent.'},{},{})}
async function createGroup(){const uid=userId();if(!uid)return toast('Connectez-vous pour créer un groupe.');const name=prompt('Nom du groupe :')?.trim();if(!name)return;try{const d=await addDoc(collection(db,'conversations'),{name,type:'group',ownerId:uid,members:[uid],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast(`Groupe « ${name} » créé.`);console.info('[Vibe] group',d.id)}catch(e){toast(`Création impossible : ${e.message}`)}}
async function createChannel(){const uid=userId();if(!uid)return toast('Connectez-vous pour créer une chaîne.');const name=prompt('Nom de la chaîne :')?.trim();if(!name)return;try{const d=await addDoc(collection(db,'channels'),{name,type:'channel',ownerId:uid,followers:[],createdAt:serverTimestamp(),updatedAt:serverTimestamp()});toast(`Chaîne « ${name} » créée.`);console.info('[Vibe] channel',d.id)}catch(e){toast(`Création impossible : ${e.message}`)}}
function mediaPicker(){const input=$('fileInput');if(!input)return;input.accept='image/*,video/*,audio/*,.pdf,.doc,.docx,.txt';input.click()}
async function handleMedia(e){const file=e.target.files?.[0];e.target.value='';const uid=userId();if(!file||!uid)return;if(!file.type.startsWith('image/')&&!file.type.startsWith('video/')&&!file.type.startsWith('audio/')&&file.size>25*1024*1024)return toast('Fichier limité à 25 Mo.');try{const url=await uploadMedia(file,'messages');const cid=window.VibeApp?.currentChatId||document.querySelector('.conversation-item.active')?.dataset.chatId;if(!cid)return toast('Ouvrez une discussion.');await addDoc(collection(db,'conversations',cid,'messages'),{uid,text:file.name,type:file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':'file',mediaUrl:url,fileName:file.name,fileSize:file.size,createdAt:serverTimestamp()});toast('Média envoyé.')}catch(err){toast(`Envoi impossible : ${err.message}`)}}
let recorder, chunks=[];
async function voice(){const uid=userId();if(!uid)return toast('Connectez-vous pour envoyer un vocal.');const cid=window.VibeApp?.currentChatId||document.querySelector('.conversation-item.active')?.dataset.chatId;if(!cid)return toast('Ouvrez une discussion.');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return toast('Les messages vocaux ne sont pas pris en charge ici.');openModal('Message vocal','<p id="vibeVoiceState">Appuyez sur Démarrer puis Arrêter.</p><div class="vibe-extra-actions"><button class="vibe-extra-primary" id="vibeVoiceStart">Démarrer</button><button class="vibe-extra-secondary" id="vibeVoiceStop" disabled>Arrêter</button></div>');$('vibeVoiceStart').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());try{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});const file=new File([blob],`vocal-${Date.now()}.webm`,{type:blob.type});const url=await uploadMedia(file,'voice');await addDoc(collection(db,'conversations',cid,'messages'),{uid,text:'🎙️ Message vocal',type:'audio',mediaUrl:url,fileName:file.name,createdAt:serverTimestamp()});toast('Message vocal envoyé.');modal?.remove()}catch(e){toast(`Envoi vocal impossible : ${e.message}`)}};recorder.start();$('vibeVoiceStart').disabled=true;$('vibeVoiceStop').disabled=false;$('vibeVoiceState').textContent='Enregistrement en cours…'}catch(e){toast('Accès au microphone refusé ou indisponible.')}};$('vibeVoiceStop').onclick=()=>{if(recorder?.state==='recording')recorder.stop()}}
function bind(){const attach=$('attachBtn');attach?.addEventListener('click',mediaPicker);$('fileInput')?.addEventListener('change',handleMedia);const add=document.createElement('div');add.className='vibe-extra-bar';add.innerHTML='<button type="button" data-extra="status">◉ Statuts</button><button type="button" data-extra="group">👥 Groupe</button><button type="button" data-extra="channel">📣 Chaîne</button><button type="button" data-extra="voice">🎙️ Vocal</button>';document.querySelector('.main-tabs')?.after(add);add.addEventListener('click',e=>{const a=e.target.closest('[data-extra]')?.dataset.extra;if(a==='status')statusUI();if(a==='group')createGroup();if(a==='channel')createChannel();if(a==='voice')voice()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
window.VibeExtras={status:statusUI,group:createGroup,channel:createChannel,media:mediaPicker,voice};
